{% set name = "python-sounddevice" %}
{% set pypi_name = "sounddevice" %}
{% set version = "0.3.15" %}
{% set sha256 = "028f6e5df83027f4bfba5d6d61e6d46eb8689f9e647825e09f539920dee17d2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - cffi
  run:
    - python
    - cffi
    - portaudio
    - numpy


test:
  imports:
    - sounddevice

about:
  home: https://python-sounddevice.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Play and Record Sound with Python
  dev_url: https://github.com/spatialaudio/python-sounddevice/

extra:
  recipe-maintainers:
    - scopatz
