{% set name = "python-sounddevice" %}
{% set pypi_name = "sounddevice" %}
{% set version = "0.3.14" %}
{% set sha256 = "c7b0f7ad86550668da55404eabcb63d4212ec622fcce86510092306b77d2e80a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - cffi
  run:
    - python
    - cffi
    - portaudio
    - numpy


test:
  imports:
    - sounddevice

about:
  home: https://python-sounddevice.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Play and Record Sound with Python'
  dev_url: https://github.com/spatialaudio/python-sounddevice/

extra:
  recipe-maintainers:
    - scopatz
