travis:
  secure:
    BINSTAR_TOKEN: bGvxjH73v7L6/o8OVIW8tzM/tOPrrk9vGxn5aet59zH6scd3hfqIDo8HM0vCsiESMwOVpbikihL9fjoZXE/P/VMTdvZzaEumMpWqkAQlzEmdDODQDAXlrjwKW6OXtTTxQvOoSUQg1q9BTI+qFfez6lM2OE2EWBeYv3LLTTT+CcfLl3peGVvNkZMt2A/4PPGAw/iV3UJCr0fMsDQQLCQB4vh9a1vyVQ0l1Bun4TyKmCwmtw9EgVc8mF5oeahF6CKo+65t60nmxAyqMqDhsr+X+U/cswaCQ9u/ziFsCCCFTRIMRLk5k66lEuXEJOT9L3EY5Qy9JuRtFPQffw884uNrBPrbLdrCEBi4MmB3e6cHKT1irigHAeKZ1FVqw6RQFERoTKrSDn0dDZ0LMi6mjBtTGOM4rI7GsPRn/B1wSqaakdWAuLEBgGOy2dRzo5Ivtn1K+N5VUg+HkOFSmFL5M+biO1O3PHS+NBAsZiLKmrM67ZuIJPhOmTcj1DLBqDCmHMwKjpn1+uPyulo870+HqnNoaiNhIYDiA0tWwtBUXsBAbQi1hxGNN927YHstkc1o4U3LD4yo4Zj/b9x3VysX9k/7pSZeAPC1qGGbyjTBBksCIKW6c8+K8Y2hkKMM2sxjutBlgHeTxdpshlJ2AAutsIh8eGKHFuVp//H0wTM5Mojh9M0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
