travis:
  secure:
    BINSTAR_TOKEN: nQ1qG9GA6GOluM9WVoLhVQMl8CP7lMqtdluY+6uvj07LIzcclgF/mSgngvnXMhTR1AjdV/L/0iM8PwlvP7uf5cLMH4+Pl+ZoSLYX1vlC3dZ5gj3M38rq6JvpG3cTJscKXlty0GFhub1Us4NJdzhf3oMSvwnOCQ7lbL1st1Lh2kXRdNoF1a01TEwxZ2mFmLohfegGldvFQ9fIm46H6+Yt0ycgckRjgmJto6PffxtvTe0eM9rDPTLSNrLBN5FSYhz/AR75etnu26b40ZSeT6heoTaLsH1L6nrPS7FQqy+rAJG6iw7omescmqPsr3siXQeQFYH6f9PIQG64BJB0NhZVAbLoPv/z3jPrI89MfKYmj7c+kxAupGs3aWcLt8doPvZ06TvNJZWVv2RPEkDtvLrwuUTqBgLAGbxO4qvq1LVJ1yTGupVdA3ZVl91OQfmLzYs6vbwYBh4D14D9eeQJdMTM6CrCD/GG0AT4j4gtY11f1K9UUjmWU2y6Vr/oz+Gm4U6UH8A173pqEjz9ePYRG923og6khsk/3MAnNzZ3mP5LB50FVp/cPtF0w5oMIEohpFN1wLb58Iy7Oc8MJJlZ017Gkqu0Cqhojw04Izsg+YVb4qiri5t7sqLe7fyfp9ED4flk+n+fYToWrYjDl3HgnT60ljp5H4AD8jCgzbfYxxc5jtE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
